baseurl: "https://azufle.github.io/spatial-epi-2023/"
title: "International Workshop on Spatial Computing for Epidemiology@ACM SIGSPATIAL 2023"
canonifyurls: true
theme: "hugo-conference"
blackfriday:
    unsafe: true

GoogleAnalytics: ""

params:
  # Conference info
  Name: "SpatialEpi@ACM SIGSPATIAL 2023"
  Description: "International Workshop on Spatial Computing for Epidemiology@ACM SIGSPATIAL 2023"
  Date: "Monday November 13, 2023"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "TBA"
  Address: "TBA"
  City:  "Hamburg"
  State: "Germany"
  Images: ["/img/logo.jpg"]
  big_logo: "/images/acmsigspatial-full.png"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - intro
    - organizer    
    - speakers
    - schedule    
    - location
    - cfp
    - deadline
  #  - contact

  # Titles which you can translate to other languages
  Titles:
    intro: "About"
    location: "Location"
    cfp: "Call For Papers"
    organizer: "Organization Committee"
    speakers: "Speakers"
    schedule: "Schedule"
    deadline: "Important Dates"
    # sponsors: "Sponsors"
    # partners: "Partners"
    contact: "Instructions for Authors"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now"
    link: ""

  intro:
    text: "The 4th ACM SIGSPATIAL International Workshop on Spatial Computing for Epidemiology (SpatialEpi’23) focuses on all aspects of modeling, simulating, mining, and understanding the spatial processes and patterns of the spread of COVID-19 and other infectious diseases. This cross-disciplinary workshop is a forum to bring together researchers in the SIGSPATIAL community as well as researchers in epidemiology. Also, this workshop is of interest to everyone who works with infectious disease data and models (not necessarily COVID19). In addition to paper presentations, this workshop will feature invited speakers keynotes from experts across the SIGSPATIAL community and epidemiology."

  cfp:
    text: "The workshop seeks high-quality full (8-10 pages) and short (4 pages) papers that have not been published in other academic outlets and are not concurrently under peer review. Once accepted, at least one author is required to register for the workshop and the ACM SIGSPATIAL conference, as well as attend the workshop to present the accepted work which will then appear in the ACM Digital Library. As SpatialEpi papers appear in the ACM SIGSPATIAL proceedings we follow the same submission process. Submission details can be found at https://sigspatial2023.sigspatial.org/camera-ready/. Following the main-conference, we also allow full papers to have a two-page appendix beyond the ten pages limit."
    url: "https://azufle.github.io/spatial-epi-2023/files/SpatialEpi2023.pdf"
    keywords: ["Contact Tracing", 
    "COVID-19 Tracking and Data Collection", 
    "COVID-19 Data Cleaning and Wrangling", 
    "Disease Spread Simulation", "COVID-19 Data Mining", 
    "Managing Uncertainty in COVID-19 Data", 
    "COVID-19 Data Query Processing", "Mapping and Visual Analytics of COVID-19", 
    "COVID-19 Effects on Human Mobility", 
    "Prescriptive Analytics for COVID-19", 
    "COVID-19 Hotspot Detection", 
    "Socioeconomic Impact of COVID-19", 
    "COVID-19 Simulation and Modeling", 
    "Spatial Analysis of COVID-19", 
    "COVID-19 and Social Media", 
    "Spatially Explicit COVID-19 Prediction Models"]

  organizer:
    general_chair: ["Andreas Züfle (Emory University)"]
    pc_chair: ["Taylor Anderson (George Mason University)", 
    "Joon-Seok Kim (Oak Ridge National Laboratories)", 
    "Amira Roess (George Mason University)"]
    pc_member: ["Song Gao (University of Wisconsin-Madison)","Alexander Hohl (The University of Utah)", "Yiqun Xie (University of Minnesota)", "Hamdi Kavak (George Mason University)", Di Yang (University of Wyoming), Zipei Fan (The University of Tokyo), Ignacio Segovia-Dominguez	(West Virginia University), Jia Yu (Washington State University), Michael Desjardins (Johns Hopkins Bloomberg School of Public Health)]
    webchair: ["Hossein Amiri (Emory University)"]

    
  deadline:
    submission: "September 18, 2023 (anywhere on earth)"
    notification: "October 11, 2023 (anywhere on earth)"
    camera ready: "To be announced"
    workshopdate: "Monday November 13, 2023"
    submissionsite: "https://easychair.org/my/conference?conf=spatialepi23"
    studentgrant: "October 11, 2023"

    
    
  #contact:
  
  speakers:
     - name: "Max Lau, Biostatistics, Rollins School of Public Health, Emory University"
       photo: "https://emoryeave.org/wp-content/uploads/MaxLau.jpeg"
       company: "Emory University"
       talk: 
         title: "ASSISTANT PROFESSOR, BIOSTATISTICS, Rollins School of Public Health"
    #     abstrct: ""
         bio: "Dr. Max Lau is Assistant Professor at Emory University, Rollins School of Public Health in the Biostatistics Department and is jointly appointed with the Epidemiology Department.  He earned his MPhil in Public Health and statistical modeling of infectious diseases at the University of Hongkong (2011).  He obtained his Ph.D. in statistical modeling of infectious diseases at Heriot-Watt University, Edinburgh (2015).  He completed his post doc work at Princeton University (2018) and began his career at Emory University in 2019.  He has developed new Bayesian methods and modelling techniques for disease data and data integration and designs and teaches graduate level machine learning and modeling classes."
         href: "https://emoryeave.org/bio/max-lau-phd/"

       
  schedule:
       - title: "Opening Remarks"
         time: "15:30-15:35"
         file: "Frontmatter.pdf"
       - title: "Keynote"
         authors: "Max Lau, , Biostatistics, Rollins School of Public Health, Emory University"
         bio: "Biostatistics, Rollins School of Public Health, Emory University"
         time: "15:35-16:30"
       - title: "Optimal Risk-aware POI Recommendations during Epidemics"
         authors: "Nina Yanin, Manos Papagelis"
         time: "16:30-16:50"
         file: "paper_1.pdf"
       - title: "EPIPOL: An Epidemiological Patterns of Life Simulation (Demonstration Paper)"
         authors: "Will Kohn, Hossein Amiri, Andreas Züfle"
         time: "16:50-17:10"
         file: "paper_2.pdf"
         
       - title: "Closing Remarks"
         time: "17:10-17:15"
         
            
